### ISSUE TITLE
Bug: tfsec warning about `tfvars` file not being used

### ISSUE THREAD

**Issue by patheard** [aquasecurity/tfsec-pr-commenter-action#11]
We've hit a bug with the action that I think is related to aquasecurity/tfsec#641.  Here's the error we're getting in our workflow:

```
+ tfsec --format=json ./config/terraform/aws
+ echo 'tfsec violations were identified, running commenter...'
+ commenter
tfsec violations were identified, running commenter...
Starting the github commenter...
The commenter failed with the following error:
invalid character '\x1b' looking for beginning of value
```

Our project has a `variables.auto.tfvars` and if we run `tfsec --format=json ./config/terraform/aws` locally, we get the warning output in the `results.json` which makes the [`json.Unmarshal`](https://github.com/aquasecurity/tfsec-pr-commenter-action/blob/v0.1.7/cmd/commenter/resultsProcessor.go#L34) unhappy:

```
[0m
[33mWarning: A tfvars file was found but not automatically used. 
Did you mean to specify the --tfvars-file flag?[39m
[0m{
	"results": [
		{
```

**Comment by owenrumney** [comment]
Hey @patheard  - thanks for raising this - I think it will be resolved in #aquasecurity/tfsec/pull/890 - I thought all these errors that fouled json format had been removed.
