### ISSUE TITLE
Missing asset in release v0.1.8

### ISSUE THREAD

**Issue by cr-benchmarkcorp** [aquasecurity/tfsec-pr-commenter-action#23]
It appears that the go binary was not published as part of the release v0.1.8.   The container build fails on step 4/6 as a result.   Can't revert to previous releases as they point at invalid urls now.

**Comment by cr-benchmarkcorp** [comment]
looking at the release.yml workflow (GitHub Actions), it appears that it is still pointing at the old tfsec repo url, which may explain why the release failed....thus leading to the issue above.

**Comment by mc-benchmarkcorp** [comment]
https://github.com/aquasecurity/tfsec-pr-commenter-action/blob/main/.goreleaser.yml

I think its still referencing the old repo and trying to create the binary artifact in the wrong location.

**Comment by olympus-fergus** [comment]
#22 is the same as this. Anyway to workaround? I tried to reference 
`aquasecurity/tfsec-pr-commenter-action@v0.1.7`
But it didn't make any difference

**Comment by mc-benchmarkcorp** [comment]
I forked the code and made the change i Suggested and have no issues creating a release with artifacts.

https://github.com/mc-benchmarkcorp/tfsec-pr-commenter-action/blob/31b67c15509e4633f74949d8fdcd87cca237b844/.goreleaser.yml#L29

https://github.com/mc-benchmarkcorp/tfsec-pr-commenter-action

https://github.com/mc-benchmarkcorp/tfsec-pr-commenter-action/releases/tag/v0.1.9

as you can see it uploads both artifacts under the release.  If you need a fix until this is corrected  fork a version and make the change.

**Comment by owenrumney** [comment]
This has been fixed - the issues came about when we moved to aquasec and missed the deployer change. Apologies for the inconvenience caused

**Comment by olympus-fergus** [comment]
Thanks! Working fine for me.
