### ISSUE TITLE
add input parameter version and fix Dockerfile

### ISSUE THREAD

**Issue by yuzujoe** [aquasecurity/tfsec-pr-commenter-action#24]
Now, the Dockerfile provided with this action will fetch the latest release version when building.
https://github.com/aquasecurity/tfsec-pr-commenter-action/blob/main/Dockerfile

So even if you want to use the specified version when using this action, you will always be provided with the latest version.
There is nothing wrong with using the latest version, but some users may want to fix the version for fear of destructive changes.

My suggestion is to add version as input information in action.yml.

```
inputs:
  version:
     description: use tfsec version
     default: latest
```

And this information is then passed as the docker arg.
https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#creating-an-action-metadata-file

I think this way users can specify the version flexibly.

Thanks

**Comment by owenrumney** [comment]
Yup - I'll try and add that today/tomorrow and rerelease
