### ISSUE TITLE
commenter fails to run after results are found

### ISSUE THREAD

**Issue by moritzheiber** [aquasecurity/tfsec-pr-commenter-action#40]
The recent update to Actions workflow has broken the commenter:

```console
+ tfsec --out=results.json --format=json --soft-fail .
+ commenter
Starting the github commenter...
The commenter failed with the following error:
strconv.Atoi: parsing "<nil>": invalid syntax
```

Relevant workflow file: https://github.com/moritzheiber/terraform-aws-oidc-github-actions-module/blob/main/.github/workflows/test.yaml#L19-L21
Relevant finding (which I'm going to ignore going forward): https://github.com/moritzheiber/terraform-aws-oidc-github-actions-module/blob/main/tests/mocks/mock_provider.tf
The `result.json` looks like this:

```json
{
	"results": [
		{
			"rule_id": "aws-misc-no-exposing-plaintext-credentials",
			"legacy_rule_id": "AWS044",
			"rule_description": "AWS provider has access credentials specified.",
			"rule_provider": "aws",
			"rule_service": "misc",
			"impact": "Exposing the credentials in the Terraform provider increases the risk of secret leakage",
			"resolution": "Don't include access credentials in plain text",
			"links": [
				"https://aquasecurity.github.io/tfsec/latest/checks/aws/misc/no-exposing-plaintext-credentials",
				"https://registry.terraform.io/providers/hashicorp/aws/latest/docs#argument-reference",
				"https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html"
			],
			"description": "Provider 'provider.aws' has an access key specified.",
			"severity": "CRITICAL",
			"status": "failed",
			"location": {
				"filename": "terraform-aws-oidc-github-actions-module/mock_provider.tf",
				"start_line": 2,
				"end_line": 2
			},
			"resource": "provider.aws"
		},
		{
			"rule_id": "general-secrets-sensitive-in-attribute",
			"legacy_rule_id": "GEN003",
			"rule_description": "Potentially sensitive data stored in block attribute.",
			"rule_provider": "general",
			"rule_service": "secrets",
			"impact": "Block attribute could be leaking secrets",
			"resolution": "Don't include sensitive data in blocks",
			"links": [
				"https://aquasecurity.github.io/tfsec/latest/checks/general/secrets/sensitive-in-attribute",
				"https://www.terraform.io/docs/state/sensitive-data.html"
			],
			"description": "Block 'provider.aws' includes a potentially sensitive attribute which is defined within the project.",
			"severity": "CRITICAL",
			"status": "failed",
			"location": {
				"filename": "terraform-aws-oidc-github-actions-module/mock_provider.tf",
				"start_line": 5,
				"end_line": 5
			},
			"resource": "provider.aws"
		}
	]
}
```

**Comment by owenrumney** [comment]
Hey @moritzheiber  - could you try again with either `@main` or `@v1.0.1` please? I've resolved an issue where there are binaries

**Comment by moritzheiber** [comment]
Hey @owenrumney, unfortunately, [it does not](https://github.com/moritzheiber/terraform-aws-oidc-github-actions-module/runs/4895357540?check_suite_focus=true#step:7:31) .. 

![image](https://user-images.githubusercontent.com/616813/150516233-88e6443e-e078-462a-8b93-d49b54165b76.png)

**Comment by owenrumney** [comment]
sorry about this @moritzheiber - let me dig into this a bit more - that error is coming from it trying to parse the patch string :thinking: 

I'll come back to you shortly

**Comment by moritzheiber** [comment]
This is what the current `result.json` looks like:

```json
{
        "results": null
}
```

Maybe it helps. Thanks for digging into it!

**Comment by owenrumney** [comment]
yeah, if I'm understanding it correctly you're updating the workflow on main and its only the `.github/<workflow>.yml` thats in the commit. I think the error is that I assume there is a PR. It's given me enough of an idea to start testing

**Comment by owenrumney** [comment]
Hey @moritzheiber  - please could you give v1.0.2 or @main a go and let me know how you get one - I think the issue should be fixed there

**Comment by moritzheiber** [comment]
That fixed it, thanks!

I wonder about the usefulness of the current Action structure, but that's the topic of an entirely different discussion

**Comment by owenrumney** [comment]
Thanks for letting me know @moritzheiber 

Please feel free to open a discussion thread with you concerns about the structure and we can talk through it there.... I very much welcome comment suggestions and criticisms (constructive)
