### ISSUE TITLE
Warning about needing to terraform init and commenter not created

### ISSUE THREAD

**Issue by amonshiz** [aquasecurity/tfsec-pr-commenter-action#41]
I am experiencing a confusing issue with `tfsec`. At 18 Jan 2022 21:36:36 -0500 I pushed a commit that included numerous new records to my PR branch. A coworker identified a typo in a resource name and so using the GitHub suggestion I committed that change directly to the PR branch at Wed, 19 Jan 2022 23:47:39 -0500. There were no changes to the step definition or the workflow in general.

I see there were a number of commits merged yesterday. Would the `--soft-fail` change have potentially introduced this issue? I'm especially curious about the new `WARNING` about needing to run `terraform init` that we were not seeing before.

Thank you for your help!

Workflow step:
```
  tfsec:
    name: tfsec - PR commenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

Output:
```
+ tfsec --out=results.json --format=json --soft-fail .
WARNING: Failed to load module: missing module with source 'github.com/org/modules.git?ref=v0.2.0/path/to/module' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'github.com/org/modules.git?ref=v0.2.0/path/to/module' -  try to 'terraform init' first
WARNING: skipped aws-iam-no-policy-wildcards due to error(s): HasDynamicTypes does not support the given type
WARNING: skipped aws-iam-no-policy-wildcards due to error(s): HasDynamicTypes does not support the given type
+ commenter
Starting the github commenter...
The commenter failed with the following error:
failed to create a new commenter. there were errors processing the PR files.
the patch details could not be resolved
```

**Comment by owenrumney** [comment]
The warning is because we previous piped STDERR to dev/null and piped stdout in json format to a file.
Now, more correctly, the output is going to file and the stdio goes to the terminal.

Soft fail means the PR won't break because of tfsec, commenter takes responsibility for exit non-zero if there are comment worth errors.

The patch details error is a bug, I think it's failing to get patch info from a non text file - do you have images or some other binary in this PR? Would be good to know if that supports the theory

**Comment by cody-carlson** [comment]
I can confirm since the new version yesterday I am getting similar errors and a failure as well.

Full Job:
```
TFSec:
    name: Terraform static analysis
    if: ${{ inputs.run-tf-sec }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Static analysis - TFSEC
        uses: aquasecurity/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif
          tfsec_args: --force-all-dirs
          
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ github.token }}

      - name: Upload TFSEC SARIF file
        if: ${{ inputs.upload-tf-sec }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          category: tfsec
          sarif_file: tfsec.sarif 
```

Error received:

```
+ tfsec --out=results.json --format=json --soft-fail .
WARNING: Failed to load module: missing module with source 'git::https://github.com/<enterprise>/<module>.git//<module>?ref=v1' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::https://github.com/<enterprise>/<module>.git.git//<module>?ref=v1' -  try to 'terraform init' first
WARNING: Failed to load module: missing module with source 'git::https://github.com/<enterprise>/<module>.git//<module>?ref=v1' -  try to 'terraform init' first
+ commenter
Starting the github commenter...
The commenter failed with the following error:
failed to create a new commenter. there were errors processing the PR files.
the patch details could not be resolved
```

I did notice from previous runs that worked before yesterday, the tfsec run command had different syntax without --out and --format specified.

**Comment by owenrumney** [comment]
HI - apologies for the inconvience, please could you try again with `@v1.0.1` or `@main` of the action - I've resolved the issue with binaries

**Comment by amonshiz** [comment]
Hi @owenrumney thank you for the fast turn around, I will try our workflow again!

Confirming there are no images or binary components to the PR.

**Comment by amonshiz** [comment]
@owenrumney Ah, thank you for improving the commenter error details!

```
The commenter failed with the following error:
failed to create a new commenter. there were errors processing the PR files.
the patch details for [module/path/dns_records/site/gmail_dkim.txt] could not be resolved
```

This _is_ a new file I have added in the PR but it is a plain text file. It is also at the path specified in the error. It is referenced via a new record like below

```
resource "cloudflare_record" "site_gmail_dkim" {
  # DKIM token generated by Google Workspace
  zone_id = data.cloudflare_zones.site_domain.zones[0].id
  name    = "google._domainkey"
  type    = "TXT"
  value   = file("${path.module}/dns_records/site/gmail_dkim.txt")
}
``` 

I believe this is properly configured but maybe I am missing something that tfsec is pointing out by not being able to find the file?

**Comment by owenrumney** [comment]
hey @amonshiz  - Am I correct in thinking that the gmail_dkim.txt has a single line in it possibly with no new line?

I don't think its your terraform, the issue is coming as I parse out the commits from the PR and I have a feeling I'm failing at getting the hunk start and end of single line entries. 

I'll keep digging, please bear with me while I work this out

**Comment by owenrumney** [comment]
Hey @amonshiz - found the issue - please could you give `v1.0.2` or `@main` a go and let me know how you get one.

Thanks for your patience

**Comment by cody-carlson** [comment]
@owenrumney  I can confirm it is now working correctly for me, hoping @amonshiz finds the same result

**Comment by amonshiz** [comment]
> hey @amonshiz - Am I correct in thinking that the gmail_dkim.txt has a single line in it possibly with no new line?
> 
> I don't think its your terraform, the issue is coming as I parse out the commits from the PR and I have a feeling I'm failing at getting the hunk start and end of single line entries.
> 
> I'll keep digging, please bear with me while I work this out

@owenrumney that is exactly what is in that file :). 

I can confirm that the most recent change does resolve the issue I was experiencing! Thank you for the fast turn around!

**Comment by ouranos** [comment]
I still have the issue with a single-line file (with a new line) with `v1.0.2`:

```
Starting the github commenter...
The commenter failed with the following error:
failed to create a new commenter. there were errors processing the PR files.
the patch details for [.terraform-version] could not be resolved
```

```diff
diff --git a/.terraform-version b/.terraform-version
index 9084fa2..781dcb0 100644
--- a/.terraform-version
+++ b/.terraform-version
@@ -1 +1 @@
-1.1.0
+1.1.3
```

**Comment by FooBartn** [comment]
This is still an issue for us as well. we have a file (agent/VERSION) that has one line in it. We're using @latest for the pr-commenter.

**Comment by FooBartn** [comment]
Added a newline to the file and it is still failing:

```
The commenter failed with the following error:
failed to create a new commenter. there were errors processing the PR files.
the patch details for [agent/VERSION] could not be resolved
```

**Comment by owenrumney** [comment]
okay, seems the patch format is different again for that - will take a look now

**Comment by owenrumney** [comment]
Hey @ouranos  and @FooBartn  - I've fixed this in v1.0.3 of the action and the patch processing can now handle single line patches `@@ -1 +1 @@` - before it was looking at patches and assuming they'd always be `@@ -1,2 +1,4 @@` type strings.

Please let me know how you get on, and thanks for your patience

**Comment by FooBartn** [comment]
Success! Thank you!

**Comment by ouranos** [comment]
Same here, thanks for the quick fix!
