### ISSUE TITLE
Allow for just running tfsec without PR commenting

### ISSUE THREAD

**Issue by moritzheiber** [aquasecurity/tfsec-pr-commenter-action#45]
I know it's in the name of the Action, but due to the lack of alternatives, I'd wish for there to be the possibility of _just installing_ `tfsec` and receiving its output in a workflow without the commenter being run.

Right now, I fear for the results getting lost because they're directly piped into `results.json` without any remedy if the workflow isn't triggered by a PR (see #40).

The added value would be that you could use this Actions _also_ for installing `tfsec` and running it on every single commit instead of _just_ for PRs, and while there are other Actions also supporting this behavior, this Action in particular is directly maintained by the company behind `tfsec` :slightly_smiling_face:

**Comment by owenrumney** [comment]
Hey @moritzheiber  - I think you've got a valid point here - How about this - https://github.com/marketplace/actions/tfsec-action

I've tested it on a few of our repos and I think it ticks the box you want. 
By default it will give you the output in default format (showing the details of the issue and code block) but you can use 

```yaml
with:
  format: csv
```

or similar if you want a terser output in the Action output.

**Comment by moritzheiber** [comment]
This works perfectly well, thanks! 👏
