### ISSUE TITLE
Add severity to comments

### ISSUE THREAD

**Issue by otyamura** [aquasecurity/tfsec-pr-commenter-action#50]
I thought it would be nice to have severity in comments, what do you think?
I think it will help us to know which one to start with when we deal with it.

This is an example.
Added severity to the end of the first line
```
tfsec check aws-s3-no-public-access-with-acl failed. [HIGH]

Resource 'aws_s3_bucket.my-bucket' has an ACL which allows public access.

For more information, see:

- https://aquasecurity.github.io/tfsec/latest/checks/aws/s3/no-public-access-with-acl
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket
- https://aws.amazon.com/premiumsupport/knowledge-center/secure-s3-resources/
```

**Comment by owenrumney** [comment]
Hey @otyamura  - thats a great suggestion - its added to v1.0.5 or use @main

![image](https://user-images.githubusercontent.com/3049157/152867260-ada6fc1d-25e3-4e08-95da-592c45f5722a.png)
